fix ts1205 error
try to fix error TS1205:
https://deno.land/posts/v1.5#stricter-type-checks-in-stable
ERROR TS1205: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.